# Generated by Django 6.0.3 on 2026-03-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0002_otpcode_patient_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
